### ISSUE TITLE
Switching between authenticated instances

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate-playground#192]
Switching between authenticated instances currently involves deleting the cookies. Also requesting a new token if the old one is expired requires that. 
Ideally you can have multiple playgrounds open with different authenticated instances and just get  again redirected to the authority provider if the token is expired.

**Comment by bobvanluijt** [comment]
@etiennedi, could you help with this one?

**Comment by etiennedi** [comment]
> Ideally you can have multiple playgrounds open with different authenticated instances
I think that's more of a long-term goal, but certainly doable.

For the short term, I'd suggest we add two things:

1. A logout button
This will allow you to switch between different instances easily, as it'll essentially clean up all local state
2. An expiry check: If the current token is present, but expired, we redirect to the token issuer.
