### ISSUE TITLE
Add example query for demo datasets

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate-playground#194]
If the weaviate instance contains a demo data set we can suggest an example query that works to quickly give user an overview on how everything works.

**Comment by bobvanluijt** [comment]
This is already in the making and will be offered via the website.

Note: https://github.com/semi-technologies/weaviate-playground/commit/bf61fb6d26d2ea4364fe4ceebb73d32fddb93c2d

I will update all when this is live.
