### ISSUE TITLE
Bugs and missing functionality

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate-playground#195]
A list of bugs and crucial functionality that currently is missing.

# Functionality

- [x] When creating the first class in an empty Weaviate, after adding a class, the panel doesn't close and reopen with the actual class (this works correctly if there are multiple classes).
- [x] can't set `vectorizeClassName`.
- [ ] no reload of panel after creating class
- [x] description doesn't show up (states: "undefined")
- [x] crossref (in properties) can't be selected
- [x] no overview of properties in the left panel.
- [x] network should be removed from the top panel
- [x] can't set `vectorizePropertyName`.
- [x] can't set `index` for a property.
- can't download or upload a schema.
  - outscoped to #197 and #198 
- next to the _pen_ in the panel, there isn't a way to _add_ a thing or action.
  - outscoped to #201 

# UX

- [x] set helper texts
- [ ] docs on the website

**Comment by etiennedi** [comment]
@bobvanluijt 

can you provide one screenshot  for each of the following items, to make sure we're talking about the same things

* description doesn't show up (states: "undefined")
* crossref (in properties) can't be selected
* no overview of properties in the left panel.
* next to the pen in the panel, there isn't a way to add a thing or action.

Thanks.

**Comment by bobvanluijt** [comment]
[![Alt text](https://img.youtube.com/vi/4Ec0liBLBsA/0.jpg)](https://www.youtube.com/watch?v=4Ec0liBLBsA)

@etiennedi The answer is in this video ⏫

**Comment by etiennedi** [comment]
@bobvanluijt  Thanks for the vid, clear.

The first one has been fixed in the meantime. The second one I'm scoping out to a new issue as that's a rather big one.

**Comment by bobvanluijt** [comment]
Kewl
